FrontEnd/Aplics.Nominix.MVC/Controllers/OrganigramaController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Aplics.Nominix.MVC.Authorize;
using Microsoft.AspNetCore.Mvc;
using Aplics.Nominix.DTOS;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.IO;
using Newtonsoft.Json;
using Aplics.Nominix.MVC.Tools;

namespace Aplics.Nominix.MVC.Controllers
{
    [AccessAuthorize]
    public class OrganigramaController : Controller
    {
        public IActionResult Main()
        {
            return View();
        }

        public IActionResult Minor()
        {

            return View();
        }

        public ActionResult AgregarPlaza(int? id)
        {
            dto_Plazas modPlazas = new dto_Plazas();

            modPlazas.Codigo = "C";
            modPlazas.PlazaSuperior = "C";
            modPlazas.Compañia = "C";
            modPlazas.Localidad = "C";
            modPlazas.Direccion = "C";
            modPlazas.Departamento = "C";
            modPlazas.Puesto = "C";
            modPlazas.TipoPlaza = "C";

            modPlazas.Autorizadas = 0;
            modPlazas.Ocupadas = 0;
            modPlazas.EventualesAutorizadas = 0;
            modPlazas.EventualesOcupadas = 0;
            modPlazas.Empleado = "C";
            modPlazas.Externo = "C";

            modPlazas.CodigoSup = "D";
            modPlazas.CompañiaSup = "D";
            modPlazas.LocalidadSup = "D";
            modPlazas.DireccionSup = "D";
            modPlazas.DepartamentoSup = "D";
            modPlazas.PuestoSup = "D";
            modPlazas.ExternoSup = "D";

            List<SelectListItem> lstCia = new List<SelectListItem>();
            List<SelectListItem> lstDireccion = new List<SelectListItem>();
            List<SelectListItem> lstLocalidad = new List<SelectListItem>();
            List<SelectListItem> lstPuesto = new List<SelectListItem>();
            List<SelectListItem> lstDepartamento = new List<SelectListItem>();

            Generales gralCia = new Generales("cias.json");
            var cia = gralCia.Read().CombosGral.OrderBy(x => x.Descripcion).ToList();
            foreach (var item in cia)
            {
                lstCia.Add(new SelectListItem() { Text = item.Descripcion, Value = item.Valor });
            }

            Generales gralDir = new Generales("direccion.json");
            var direccion = gralDir.Read().CombosGral.OrderBy(x => x.Descripcion).ToList();
            foreach (var itemDir in direccion)
            {
                lstDireccion.Add(new SelectListItem() { Text = itemDir.Descripcion, Value = itemDir.Valor });
            }

            Generales gralLoc = new Generales("localidad.json");
            var localidad = gralLoc.Read().CombosGral.OrderBy(x => x.Descripcion).ToList();
            foreach (var itemloc in localidad)
            {
                lstLocalidad.Add(new SelectListItem() { Text = itemloc.Descripcion, Value = itemloc.Valor });
            }

            Generales gralPue = new Generales("puesto.json");
            var puesto = gralPue.Read().CombosGral.OrderBy(x => x.Descripcion).ToList();
            foreach (var itemPue in puesto)
            {
                lstPuesto.Add(new SelectListItem() { Text = itemPue.Descripcion, Value = itemPue.Valor });
            }

            Generales gralDepto = new Generales("departamento.json");
            var departamento = gralDepto.Read().CombosGral.OrderBy(x => x.Descripcion).ToList();
            foreach (var itemDepto in departamento)
            {
                lstDepartamento.Add(new SelectListItem() { Text = itemDepto.Descripcion, Value = itemDepto.Valor });
            }

            ViewBag.comboCias = lstCia;
            ViewBag.comboDireccion = lstDireccion;
            ViewBag.comboLocalidad = lstLocalidad;
            ViewBag.comboPuesto = lstPuesto;
            ViewBag.comboDepartamento = lstDepartamento;

            return View(modPlazas);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AgregarPlaza(dto_Plazas modPlazas)
        {
            //llamada a api servicio para agregar el registro
            return View(modPlazas);
        }

        public ActionResult BorrarPlaza(int? id)
        {
            //aca se debeera de obtener los datos del dto de plazas filtrado por ID del API

            dto_Plazas modPlazas = new dto_Plazas();

            modPlazas.CodigoPlazaSeleccionada = "PS SSS";
            modPlazas.DescripcionPlaza = "PLAZA SELECCIONADA";

            modPlazas.Compañia = "C";
            modPlazas.Localidad = "C";
            modPlazas.Direccion = "C";
            modPlazas.Departamento = "C";
            modPlazas.Puesto = "C";
            modPlazas.TipoPlaza = "C";

            modPlazas.Autorizadas = 0;
            modPlazas.Ocupadas = 0;
            modPlazas.EventualesAutorizadas = 0;
            modPlazas.EventualesOcupadas = 0;
            modPlazas.Empleado = "C";
            modPlazas.Externo = "C";


            return View(modPlazas);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult BorrarPlaza(dto_Plazas modPlazas)
        {
            //aca se debeera de obtener los datos del dto de plazas filtrado por ID del API

            //dto_Plazas modPlazas = new dto_Plazas();

            //modPlazas.CodigoPlazaSeleccionada = "PS SSS";
            //modPlazas.DescripcionPlaza = "PLAZA SELECCIONADA";

            //modPlazas.Compañia = "C";
            //modPlazas.Localidad = "C";
            //modPlazas.Direccion = "C";
            //modPlazas.Departamento = "C";
            //modPlazas.Puesto = "C";
            //modPlazas.TipoPlaza = "C";

            //modPlazas.Autorizadas = 0;
            //modPlazas.Ocupadas = 0;
            //modPlazas.EventualesAutorizadas = 0;
            //modPlazas.EventualesOcupadas = 0;
            //modPlazas.Empleado = "C";
            //modPlazas.Externo = "C";


            return View();

        }

        public ActionResult ModificarPlaza(int? id)
        {
            dto_Plazas modPlazas = new dto_Plazas();

            modPlazas.CodigoPlazaSeleccionada = "PS SSS";
            modPlazas.DescripcionPlaza = "PLAZA SELECCIONADA";

            modPlazas.Compañia = "C";
            modPlazas.Localidad = "C";
            modPlazas.Direccion = "C";
            modPlazas.Departamento = "C";
            modPlazas.Puesto = "C";
            modPlazas.TipoPlaza = "C";

            modPlazas.Autorizadas = 0;
            modPlazas.Ocupadas = 0;
            modPlazas.EventualesAutorizadas = 0;
            modPlazas.EventualesOcupadas = 0;
            modPlazas.Empleado = "C";
            modPlazas.Externo = "C";

            List<SelectListItem> lstCia = new List<SelectListItem>();
            List<SelectListItem> lstDireccion = new List<SelectListItem>();
            List<SelectListItem> lstLocalidad = new List<SelectListItem>();
            List<SelectListItem> lstPuesto = new List<SelectListItem>();
            List<SelectListItem> lstDepartamento = new List<SelectListItem>();

            Generales gralCia = new Generales("cias.json");
            var cia = gralCia.Read().CombosGral.OrderBy(x => x.Descripcion).ToList();
            foreach (var item in cia)
            {
                if (item.Valor == "2")
                {
                    lstCia.Add(new SelectListItem() { Text = item.Descripcion, Value = item.Valor, Selected = true });
                }
                lstCia.Add(new SelectListItem() { Text = item.Descripcion, Value = item.Valor });
            }

            Generales gralDir = new Generales("direccion.json");
            var direccion = gralDir.Read().CombosGral.OrderBy(x => x.Descripcion).ToList();
            foreach (var itemDir in direccion)
            {
                if (itemDir.Valor == "2")
                {
                    lstDireccion.Add(new SelectListItem() { Text = itemDir.Descripcion, Value = itemDir.Valor, Selected=true });
                }
                lstDireccion.Add(new SelectListItem() { Text = itemDir.Descripcion, Value = itemDir.Valor });
            }

            Generales gralLoc = new Generales("localidad.json");
            var localidad = gralLoc.Read().CombosGral.OrderBy(x => x.Descripcion).ToList();
            foreach (var itemloc in localidad)
            {
                if (itemloc.Valor == "2")
                {
                    lstLocalidad.Add(new SelectListItem() { Text = itemloc.Descripcion, Value = itemloc.Valor, Selected=true });
                }
                lstLocalidad.Add(new SelectListItem() { Text = itemloc.Descripcion, Value = itemloc.Valor });
            }

            Generales gralPue = new Generales("puesto.json");
            var puesto = gralPue.Read().CombosGral.OrderBy(x => x.Descripcion).ToList();
            foreach (var itemPue in puesto)
            {
                if (itemPue.Valor == "2")
                {
                    lstPuesto.Add(new SelectListItem() { Text = itemPue.Descripcion, Value = itemPue.Valor, Selected=true });
                }
                lstPuesto.Add(new SelectListItem() { Text = itemPue.Descripcion, Value = itemPue.Valor });
            }

            Generales gralDepto = new Generales("departamento.json");
            var departamento = gralDepto.Read().CombosGral.OrderBy(x => x.Descripcion).ToList();
            foreach (var itemDepto in departamento)
            {
                if (itemDepto.Valor == "2")
                {
                    lstDepartamento.Add(new SelectListItem() { Text = itemDepto.Descripcion, Value = itemDepto.Valor, Selected=true });
                }
                lstDepartamento.Add(new SelectListItem() { Text = itemDepto.Descripcion, Value = itemDepto.Valor });
            }

            ViewBag.comboCias = lstCia;
            ViewBag.comboDireccion = lstDireccion;
            ViewBag.comboLocalidad = lstLocalidad;
            ViewBag.comboPuesto = lstPuesto;

FrontEnd/Aplics.Nominix.MVC/Views/Organigrama/AgregarPlaza.cshtml
@model Aplics.Nominix.DTOS.dto_Plazas

<div class="container">
      <div class="row">
        <div class="col-md-12">
          <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="#">Nomina</a></li>
              <li class="breadcrumb-item active" aria-current="page">
                Agregar Plaza
              </li>
            </ol>
          </nav>
        </div>
        <div class="col-md-12">
          <div class="card">
            <div class="card-body">
              <div class="container">
                <div class="row mt-3">
                  <div class="col-md-12">

                    @using (Html.BeginForm("AgregarPlaza", "Organigrama", FormMethod.Post, new { @id = "form1" }))
                    { 
                      <div class="card">
                          <div class="card-header">
                              <h4 class="text-center">Datos de la Plaza Superior</h4>
                          </div>

                          @Html.AntiForgeryToken()

                          <div class="card-body">
                              <div class="container">
                                  <div class="row">
                                      <div class="col-md-4">
                                          <p>Plaza: <b>@Model.CodigoSup</b></p>
                                          <p>Compañia:<b>@Model.CompañiaSup</b></p>
                                          <p>Localidad:<b>@Model.LocalidadSup</b></p>
                                      </div>
                                      <div class="col-md-4">
                                          <p>Direccion: <b>@Model.DireccionSup</b></p>
                                          <p>Departamento: <b>@Model.DepartamentoSup</b></p>
                                          <p>Puesto: <b>@Model.PuestoSup</b></p>
                                          <p>Externo Sup: <b>@Model.ExternoSup</b></p>
                                      </div>
                                  </div>
                                  <div class="row d-flex justify-content-end align-items-center">
                                      <button type="submit" class="btn btn-primary btn-sm btn-block"><i class="fa fa-envelope"></i>Agregar Plaza</button>
                                      @*<button type="submit" class="bx bx-save"><span>GUARDAR</span></button>*@
                                      @*<span><i class="bx bx-save"></i>HOLA MUNDO</span>*@
                                  </div>

                                  <div class="card-header">
                                      <h4 class="text-center">Plaza Nueva</h4>
                                  </div>

                                  <div class="form-group">
                                      <label for="exampleInputEmail1">Plaza</label>
                                      @Html.EditorFor(model => model.Codigo, new { htmlAttributes = new { @class = "form-control", id = "exampleInputEmail1" } })
                                  </div>

                                  <div class="form-group">
                                      <label for="exampleFormControlSelect1">Compañia</label>
                                      @Html.DropDownList("compañia", (IEnumerable<SelectListItem>)ViewBag.comboCias, htmlAttributes: new { @class = "form-control form-control-lg", @id = "inputCia" })
                                  </div>

                                  <div class="form-group">
                                      <label for="exampleFormControlSelect1">Localidad</label>
                                      @Html.DropDownList("localidad", (IEnumerable<SelectListItem>)ViewBag.comboLocalidad, htmlAttributes: new { @class = "form-control form-control-lg", @id = "inputLoc" })
                                  </div>

                                  <div class="form-group">
                                      <label for="exampleFormControlSelect1">Direccion</label>
                                      @Html.DropDownList("direccion", (IEnumerable<SelectListItem>)ViewBag.comboDireccion, htmlAttributes: new { @class = "form-control form-control-lg", @id = "inputDir" })
                                  </div>

                                  <div class="form-group">
                                      <label for="exampleFormControlSelect1">Departamento</label>
                                      @Html.DropDownList("departamento", (IEnumerable<SelectListItem>)ViewBag.comboDepartamento, htmlAttributes: new { @class = "form-control form-control-lg", @id = "inputDepto" })
                                  </div>

                                  <div class="form-group">
                                      <label for="exampleFormControlSelect1">Puesto</label>
                                      @Html.DropDownList("puesto", (IEnumerable<SelectListItem>)ViewBag.comboPuesto, htmlAttributes: new { @class = "form-control form-control-lg", @id = "inputPue" })
                                  </div>

                                  <div class="card-header">
                                      <h4 class="text-center">Configuracion Plaza</h4>
                                  </div>

                                  <div class="form-group">
                                      <label for="exampleInputEmail1">Autorizadas</label>
                                      @Html.EditorFor(model => model.Autorizadas, new { htmlAttributes = new { @class = "form-control", id = "inputAutorizadas" } })
                                  </div>

                                  <div class="form-group">
                                      <label for="exampleInputEmail1">Ocupadas</label>
                                      @Html.EditorFor(model => model.Ocupadas, new { htmlAttributes = new { @class = "form-control", id = "inputAutorizadas" } })
                                  </div>

                                  <div class="form-group">
                                      <label for="exampleInputEmail1">Eventuales Autorizadas</label>
                                      @Html.EditorFor(model => model.EventualesAutorizadas, new { htmlAttributes = new { @class = "form-control", id = "inputAutorizadas" } })
                                  </div>

                                  <div class="form-group">
                                      <label for="exampleInputEmail1">Eventuales Ocupadas</label>
                                      @Html.EditorFor(model => model.EventualesOcupadas, new { htmlAttributes = new { @class = "form-control", id = "inputAutorizadas" } })
                                  </div>

                                  <div class="form-group">
                                      @Html.EditorFor(model => model.Externo, new { htmlAttributes = new { @class = "form-control", id = "inputAutorizadas" } })
                                  </div>

                                  @*<div class="card-header">
                                      <h4 class="text-center">Empleados</h4>
                                  </div>

                                  @Html.Partial("_EmpleadosPlazas", Model.Empleados)*@
                                  

                                  @*<div class="form-group">
            <div class="col-md-4">
                <p><b>Cesar Platon Hohlatcheff Avila</b></p>
            </div>
        </div>*@


                              </div>
                          </div>
                      </div>
                    }
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

FrontEnd/Aplics.Nominix.MVC/Views/Organigrama/BorrarPlaza.cshtml
@model Aplics.Nominix.DTOS.dto_Plazas

@using (Html.BeginForm("BorrarPlaza", "Organigrama", FormMethod.Post, new { @id = "form1" }))
{
    <div class="col-md-4">
        <div class="ibox ">
            @Html.AntiForgeryToken()
            <div class="ibox-title">
                <h5>Borrar Plaza</h5>
            </div>
            <div>
                <div class="ibox-content no-padding border-left-right">
                    <img alt="image" class="img-fluid" src="img/profile_big.jpg">
                </div>
                <div class="ibox-content profile-content">
                    <h4><strong>@Model.DescripcionPlaza </strong></h4>
                    <h5>
                        Acerca de la Plaza
                    </h5>
                    <p><i class="fa fa-map-marker"></i>@Html.DisplayNameFor(model => model.Compañia)</p>
                    <p><i class="fa fa-map-marker"></i>Departamento: @Model.Departamento</p>
                    <p><i class="fa fa-map-marker"></i>Puesto: @Model.Puesto</p>
                    <p><i class="fa fa-map-marker"></i>Localidad: @Model.Localidad</p>
                    <p><i class="fa fa-map-marker"></i>Plazas Autorizadas: @Model.Autorizadas</p>
                    <p><i class="fa fa-map-marker"></i>Plazas Ocupadas: @Model.Ocupadas</p>
                    <p><i class="fa fa-map-marker"></i>Plazas Eventuales Autorizadas: @Model.EventualesAutorizadas</p>
                    <p><i class="fa fa-map-marker"></i>Plazas Eventuales Ocupadas: @Model.EventualesOcupadas</p>
                    <p><i class="fa fa-map-marker"></i>Externo: @Model.Externo</p>
                    <div class="user-button">
                        <div class="row">
                            <div class="col-md-6">
                                <button type="submit" class="btn btn-primary btn-sm btn-block"><i class="fa fa-envelope"></i>Borrar Plaza</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
}

FrontEnd/Aplics.Nominix.MVC/Views/Organigrama/ConsultarPlaza.cshtml
@model Aplics.Nominix.DTOS.dto_Plazas

<div class="container">
      <div class="row">
        <div class="col-md-12">
          <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="#">Nomina</a></li>
              <li class="breadcrumb-item active" aria-current="page">
                Modificar Plaza
              </li>
            </ol>
          </nav>
        </div>
        <div class="col-md-12">
          <div class="card">
            <div class="card-body">
              <div class="container">
                <div class="row mt-3">
                  <div class="col-md-12">

                    @using (Html.BeginForm("ConsultarPlaza", "Organigrama", FormMethod.Post, new { @id = "form1" }))
                    { 
                      <div class="card">
                          <div class="card-header">
                              <h4 class="text-center">Datos de la Plaza Superior</h4>
                          </div>

                          @Html.AntiForgeryToken()

                          <div class="card-body">
                              <div class="container">
                                  <div class="row">
                                      <div class="col-md-4">
                                          <p>Plaza: <b>@Model.CodigoSup</b></p>
                                          <p>Compañia:<b>@Model.CompañiaSup</b></p>
                                          <p>Localidad:<b>@Model.LocalidadSup</b></p>
                                      </div>
                                      <div class="col-md-4">
                                          <p>Direccion: <b>@Model.DireccionSup</b></p>
                                          <p>Departamento: <b>@Model.DepartamentoSup</b></p>
                                          <p>Puesto: <b>@Model.PuestoSup</b></p>
                                          <p>Externo Sup: <b>@Model.ExternoSup</b></p>
                                      </div>
                                  </div>
                                  <div class="card-header">
                                      <h4 class="text-center">Datos de la Plaza</h4>
                                  </div>
                                  <div class="row">
                                      <div class="col-md-4">
                                          <p>Plaza: <b>@Model.Codigo</b></p>
                                          <p>Compañia:<b>@Model.Compañia</b></p>
                                          <p>Localidad:<b>@Model.Localidad</b></p>
                                      </div>
                                      <div class="col-md-4">
                                          <p>Direccion: <b>@Model.Direccion</b></p>
                                          <p>Departamento: <b>@Model.Departamento</b></p>
                                          <p>Puesto: <b>@Model.Puesto</b></p>
                                          <p>Externo Sup: <b>@Model.Externo</b></p>
                                      </div>
                                  </div>
                                 
                                   <div class="card-header">
                                      <h4 class="text-center">Empleados</h4>
                                  </div>

                                  @Html.Partial("_EmpleadosPlazas", Model.Empleados)

                              </div>
                          </div>
                      </div>
                    }
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

FrontEnd/Aplics.Nominix.MVC/Views/Organigrama/Main.cshtml
@{
    ViewBag.Title = "Main";
}

@section Styles{

    @*ESTILO PARA ORGCHART*@
    <style>
        #chart {
            width: 100%;
            height: 100%;
        }

        .classCard {
            background-color: aquamarine;
            border-radius: 12px;
            font-family: 'Lucida Console',Courier New, Courier, monospace;
            font-size: 8px;
            width: 100px;
        }
    </style>

    <link href="~/css/StyleSheet.css" rel="stylesheet">
    <link href="~/css/context-menu.css" rel="stylesheet" />
}



<div class="wrapper wrapper-content">
    <div class="row">
        <div class="col-lg-12">

            <div class="context-menu-container" id="context-menu-items">
                <ul>
                    <li>Item 1</li>
                    <li>Item 2</li>
                    <li>Item 3</li>
                    <li>Re-enable item 2</li>
                    <li class="warning">Warning Item</li>
                    <li class="danger">Risky Item</li>
                </ul>
            </div>

            <h2>Adding Context Menu within P tag</h2>
            <p>Here is a context menu in a &lt;p&gt; <span class="context-menu" data-container-id="context-menu-items"></span></p>

            <div class="context-menu" data-container-id="context-menu-items" data-row-id="1">
                <p>HOLA MUNEDO</p>
            </div>

            @*<div class="container">

            <table class="table table-striped">
                <tr>
                    <th>Col 1</th>
                    <th>Col 2</th>
                    <th>&nbsp;</th>
                </tr>
                <tr>
                    <td>Item 1</td>
                    <td>Item 2</td>
                    <td class="context-menu" data-container-id="context-menu-items" data-row-id="1"></td>
                </tr>
                <tr>
                    <td>Item 3</td>
                    <td>Item 4 </td>
                    <td class="context-menu" data-container-id="context-menu-items" data-row-id="2"></td>
                </tr>
            </table>

            <h2>Add context menu to a heading text</h2>
            <h3 class="context-menu" data-container-id="context-menu-items">Here is an h3 with a context menu</h3>
        </div>*@

            <div class="text-center m-t-lg">
                <div id="chart"></div>
            </div>

            <div id="dialog" style="display: none">
            </div>
        </div>
    </div>
</div>

@section scripts{
    <script src="https://code.jquery.com/jquery-1.12.4.min.js"></script>
    <script src="~/js/context-menu.js?v=1.0.0.1"></script>

    @*LIBRERIAS PARA ORGCHART*@
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>

    @*SCRIPTS PARA MENU CONTEXTUAL*@
    <script>
        var tableContextMenu = null;

        $(document).ready(function () {
            var options = {
                openCallBack: function (contextMenu) {
                    contextMenu.disableMenuItem("Warning Item");
                }
            };
            tableContextMenu = new ContextMenu("context-menu-items", menuItemClickListener);
            tableContextMenu.disableMenuItem(1);
        });

        function menuItemClickListener(menu_item, parent) {
            if (menu_item.text() === "Re-enable item 2") {
                tableContextMenu.enableMenuItem("Item 2");
                //As we can't enable item 2 again, then why not disable the menu item to re-enable
                tableContextMenu.disableMenuItem(3);
            }
            else {
                alert("Menu Item Clicked: " + menu_item.text() + "\nRecord ID: " + parent.attr("data-row-id"));
            }
        }
    </script>

    @*ORGANIGRAMA CHART*@
<script type="text/javascript">

        google.load("visualization", "1", { packages: ["orgchart"] });
        google.setOnLoadCallback(drawChart);

        function drawChart() {
            $.ajax({
                type: "POST",
                url: "/Organigrama/AjaxMethod",
                data: '{}',
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                success: function (r) {

                    var data = new google.visualization.DataTable();
                    data.addColumn('string', 'Entity');
                    data.addColumn('string', 'ParentEntity');
                    data.addColumn('string', 'ToolTip');

                    for (var i = 0; i < r.length; i++) {
                        var employeeId = r[i][0].toString();
                        var employeeName = r[i][1];
                        var designation = r[i][2];
                        var reportingManager = r[i][3] != null ? r[i][3].toString() : '';

                        data.addRows(
                            [
                                [
                                    {
                                        v: employeeId,
                                        f: '<div class="context-menu" data-container-id="context-menu-items" data-row-id="100"><img src = "/images/personCard.png" width=50 height=50 /></div><div><span>' + designation + '</span></div><div><a href="/Organigrama/AgregarPlaza/' + employeeId + '">AGREGAR</a></div><div><a href="/Organigrama/ModificarPlaza/' + employeeId + '">MODIFICAR</a></div><div><a href="/Organigrama/BorrarPlaza/' + employeeId + '">BORRAR</a></div><div><a href="/Organigrama/ConsultarPlaza/' + employeeId + '">CONSULTAR</a></div>'
                                    },
                                    reportingManager,
                                    designation,
                                ]
                            ]
                        );
                    };

                    //for (var i = 0; i < r.length; i++) {
                    //    data.setRowProperty(i, 'style', 'width:100px');
                    //}

                    /*data.setRowProperty(3, 'style', 'border: 10px solid green');*/
                    //data.setRowProperty(3, 'style', 'width:100px');
                    //data.setRowProperty(3, 'style', 'width:100px');

                    var chart = new google.visualization.OrgChart($("#chart")[0]);

                    /*google.visualization.events.addListener(chart, 'select', toggleDisplay);*/

                    //google.visualization.events.addListener(chart, 'select', function () {
                    //    location.href = 'http://www.google.com';
                    //});



                    chart.draw(data, { allowCollapse: true, allowHtml: true, nodeClass: 'classCard' });
                    /*chart.draw(data, { allowHtml: true });*/



                    //function toggleDisplay() {
                    //    var selection = chart.getSelection();
                    //    alert('hola mundo');
                    //    console.log(selection[0]);

                    //    var selection = chart.getSelection();
                    //    var row;
                    //    if (selection.length == 0) {
                    //        row = previous;
                    //    }
                    //    else {
                    //        row = selection[0].row;
                    //        previous = row;
                    //    }
                    //    var collapsed = chart.getCollapsedNodes();
                    //    var collapse = (collapsed.indexOf(row) == -1);
                    //    chart.collapse(row, collapse);
                    //    chart.setSelection([{ row: row, column: null }]);
                    //}

                },
                failure: function (r) {
                    alert(r);
                },
                error: function (r) {
                    alert(r);
                }
            });

        }

</script>
}